### ISSUE TITLE
PDF generation with images

### ISSUE THREAD

**Issue by guyguy333** [ladybirdweb/faveo-helpdesk#114]
Hi Faveo Team,

In case you've for example images in the signature of a user replying to a ticket and you generate the PDF, you get "Image not found or type unknown" instead of images.

Thanks

**Comment by mathieu-aubin** [comment]
Hi, again -- which your webserver? Any screenshot? Url?

**Comment by guyguy333** [comment]
Hi @mathieu-aubin again,

As in the other thread, I'm using Faveo v1.0.7.8 (f08b7e8) with Apache 2.4.6 and PHP 5.6.13 on CentOS 7.

I attached some screenshots. The first one is the header of the PDF and the second one is a signature of an agent containing images who replied by mail.

![header](https://cloud.githubusercontent.com/assets/4040959/16893958/f7c70926-4b47-11e6-8c22-0cd25e8fe7c8.png)

![signature](https://cloud.githubusercontent.com/assets/4040959/16893960/f9ae7ff8-4b47-11e6-8826-0dfea4be4d10.png)

Sometimes, an error 500 also occurs. Here is the error stack:

`Next exception 'ErrorException' with message 'imagejpeg() expects parameter 1 to be resource, boolean given (View: /home/*****/faveo-helpdesk/resources/views/themes/default1/agent/helpdesk/ticket/pdf.blade.php)' in /home/*****/faveo-helpdesk/storage/framework/views/acf56a93c9795e903e177f73fc4c75612ae65e5d.php:103
Stack trace:
#0 /home/*****/faveo-helpdesk/vendor/laravel/framework/src/Illuminate/View/Engines/PhpEngine.php(44): Illuminate\View\Engines\CompilerEngine->handleViewException(Object(ErrorException), 1)
#1 /home/*****/faveo-helpdesk/vendor/laravel/framework/src/Illuminate/View/Engines/CompilerEngine.php(59): Illuminate\View\Engines\PhpEngine->evaluatePath('/home/*****...', Array)
#2 /home/*****/faveo-helpdesk/vendor/laravel/framework/src/Illuminate/View/View.php(149): Illuminate\View\Engines\CompilerEngine->get('/home/*****...', Array)
#3 /home/*****/faveo-helpdesk/vendor/laravel/framework/src/Illuminate/View/View.php(120): Illuminate\View\View->getContents()
#4 /home/*****/faveo-helpdesk/vendor/laravel/framework/src/Illuminate/View/View.php(85): Illuminate\View\View->renderContents()
#5 /home/*****/faveo-helpdesk/app/Http/Controllers/Agent/helpdesk/TicketController.php(522): Illuminate\View\View->render()
#6 [internal function]: App\Http\Controllers\Agent\helpdesk\TicketController->ticket_print('7')
#7 /home/*****/faveo-helpdesk/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(80): call_user_func_array(Array, Array)
#8 /home/*****/faveo-helpdesk/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(146): Illuminate\Routing\Controller->callAction('ticket_print', Array)
#9 /home/*****/faveo-helpdesk/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(94): Illuminate\Routing\ControllerDispatcher->call(Object(App\Http\Controllers\Agent\helpdesk\TicketController), Object(Illuminate\Routing\Route), 'ticket_print')
#10 [internal function]: Illuminate\Routing\ControllerDispatcher->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#11 /home/*****/faveo-helpdesk/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(52): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#12 /home/*****/faveo-helpdesk/app/Http/Middleware/Authenticate.php(52): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#13 [internal function]: App\Http\Middleware\Authenticate->handle(Object(Illuminate\Http\Request), Object(Closure))
#14 /home/*****/faveo-helpdesk/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(136): call_user_func_array(Array, Array)
#15 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#16 /home/*****/faveo-helpdesk/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(32): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#17 [internal function]: Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#18 /home/*****/faveo-helpdesk/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#19 /home/*****/faveo-helpdesk/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(96): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#20 /home/*****/faveo-helpdesk/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(54): Illuminate\Routing\ControllerDispatcher->callWithinStack(Object(App\Http\Controllers\Agent\helpdesk\TicketController), Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request), 'ticket_print')
#21 /home/*****/faveo-helpdesk/vendor/laravel/framework/src/Illuminate/Routing/Route.php(174): Illuminate\Routing\ControllerDispatcher->dispatch(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request), 'App\\Http\\Contro...', 'ticket_print')
#22 /home/*****/faveo-helpdesk/vendor/laravel/framework/src/Illuminate/Routing/Route.php(140): Illuminate\Routing\Route->runController(Object(Illuminate\Http\Request))
#23 /home/*****/faveo-helpdesk/vendor/laravel/framework/src/Illuminate/Routing/Router.php(724): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request))
#24 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#25 /home/*****/faveo-helpdesk/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(52): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#26 /home/*****/faveo-helpdesk/app/Http/Middleware/CheckUpdate.php(35): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#27 [internal function]: App\Http\Middleware\CheckUpdate->handle(Object(Illuminate\Http\Request), Object(Closure))
#28 /home/*****/faveo-helpdesk/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(136): call_user_func_array(Array, Array)
#29 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#30 /home/*****/faveo-helpdesk/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(32): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#31 /home/*****/faveo-helpdesk/app/Http/Middleware/LanguageMiddleware.php(21): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#32 [internal function]: App\Http\Middleware\LanguageMiddleware->handle(Object(Illuminate\Http\Request), Object(Closure))
#33 /home/*****/faveo-helpdesk/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(136): call_user_func_array(Array, Array)
#34 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#35 /home/*****/faveo-helpdesk/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(32): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#36 /home/*****/faveo-helpdesk/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(49): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#37 [internal function]: Illuminate\View\Middleware\ShareErrorsFromSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#38 /home/*****/faveo-helpdesk/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(136): call_user_func_array(Array, Array)
#39 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#40 /home/*****/faveo-helpdesk/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(32): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#41 /home/*****/faveo-helpdesk/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(62): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#42 [internal function]: Illuminate\Session\Middleware\StartSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#43 /home/*****/faveo-helpdesk/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(136): call_user_func_array(Array, Array)
#44 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#45 /home/*****/faveo-helpdesk/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(32): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#46 /home/*****/faveo-helpdesk/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php(37): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#47 [internal function]: Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse->handle(Object(Illuminate\Http\Request), Object(Closure))
#48 /home/*****/faveo-helpdesk/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(136): call_user_func_array(Array, Array)
#49 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#50 /home/*****/faveo-helpdesk/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(32): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#51 /home/*****/faveo-helpdesk/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(59): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#52 [internal function]: Illuminate\Cookie\Middleware\EncryptCookies->handle(Object(Illuminate\Http\Request), Object(Closure))
#53 /home/*****/faveo-helpdesk/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(136): call_user_func_array(Array, Array)
#54 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#55 /home/*****/faveo-helpdesk/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(32): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#56 /home/*****/faveo-helpdesk/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/CheckForMaintenanceMode.php(44): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#57 [internal function]: Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode->handle(Object(Illuminate\Http\Request), Object(Closure))
#58 /home/*****/faveo-helpdesk/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(136): call_user_func_array(Array, Array)
#59 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#60 /home/*****/faveo-helpdesk/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(32): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#61 [internal function]: Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#62 /home/*****/faveo-helpdesk/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#63 /home/*****/faveo-helpdesk/vendor/laravel/framework/src/Illuminate/Routing/Router.php(726): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#64 /home/*****/faveo-helpdesk/vendor/laravel/framework/src/Illuminate/Routing/Router.php(699): Illuminate\Routing\Router->runRouteWithinStack(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request))
#65 /home/*****/faveo-helpdesk/vendor/laravel/framework/src/Illuminate/Routing/Router.php(675): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
#66 /home/*****/faveo-helpdesk/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(246): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#67 [internal function]: Illuminate\Foundation\Http\Kernel->Illuminate\Foundation\Http\{closure}(Object(Illuminate\Http\Request))
#68 /home/*****/faveo-helpdesk/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(52): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#69 /home/*****/faveo-helpdesk/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/CheckForMaintenanceMode.php(44): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#70 [internal function]: Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode->handle(Object(Illuminate\Http\Request), Object(Closure))
#71 /home/*****/faveo-helpdesk/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(136): call_user_func_array(Array, Array)
#72 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#73 /home/*****/faveo-helpdesk/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(32): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#74 [internal function]: Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#75 /home/*****/faveo-helpdesk/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#76 /home/*****/faveo-helpdesk/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(132): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#77 /home/*****/faveo-helpdesk/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(99): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter(Object(Illuminate\Http\Request))
#78 /home/*****/faveo-helpdesk/public/index.php(53): Illuminate\Foundation\Http\Kernel->handle(Object(Illuminate\Http\Request))
#79 {main}
`

Thanks

**Comment by mathieu-aubin** [comment]
@guyguy333 -- Hi Thanks for the precisions!
I have corrected the problem quite easily....

Looking back at pdf generation... Most php developers (including laravel framework i just noticed) use a tool/library called
<a  href="https://github.com/dompdf"><img src="https://avatars0.githubusercontent.com/u/2776605?v=3&s=200" alt="DOMPDF On GitHub"/></a>
File dompdf_config.custom.inc.php is the culprit.

Configuration file is in: `vendor/dompdf/dompdf/dompdf_config.custom.inc.php`
```bash
root@XXX:/var/test/helpdesk.speedinternet.ca# updatedb
root@XXX:/var/test/helpdesk.speedinternet.ca# locate -i DOMPDF_CONFIG
/var/test/helpdesk.speedinternet.ca/vendor/dompdf/dompdf/dompdf_config.custom.inc.php
/var/test/helpdesk.speedinternet.ca/vendor/dompdf/dompdf/dompdf_config.inc.php
```
Uncomment bottom line:
```php
//define("DOMPDF_ENABLE_REMOTE", true);
```
RESTART BOTH WEBSERVER AND PHP PROCESSES
Regenerage the PDF, should work.

Thanks!
Bonus:
To install mlocate on CentOS (not needed but convenient -- use updatedb to refresh files once in a while)
```bash
yum install mlocate
```
-- Output tests --
<a href="http://i.imgur.com/W4nEQAM.png">
  <img src="http://imgur.com/W4nEQAMl.png" />
</a><br>
<a href="http://i.imgur.com/ql312TY.png">
  <img src="http://imgur.com/ql312TYl.png" />
</a>

**Comment by guyguy333** [comment]
👍

Thanks  @mathieu-aubin, it works. It doesn't solve error 500 for another PDF generation with another ticket but I guess it's another issue.

**Comment by mathieu-aubin** [comment]
@guyguy333 
Guillaume, as far as the 500 error, if you wouldn't mind showing me your apache vhost config in private..
you can mail it using [this link](http://bit.ly/github-msg)

**Comment by sujit223** [comment]
please have a check of your server **xdebug.max_nesting_level** in php.ini. If you cant find one please add `xdebug.max_nesting_level = 500`

**Comment by mathieu-aubin** [comment]
of course, that's if you have xdebug extension installed.
```bash
sudo yum install mlocate
sudo updatedb
sudo locate xdebug.ini
```
if you have no output, try looking for a suitable xdebug package using (php 5.6.13 in your case, used for reference):
```bash
php -v
sudo yum search xdebug
sudo yum install <corresponding_package_name>
```
then you can `sudo locate php.ini` to then do something like;

`echo -e "zend_extension=xdebug.so\nxdebug.max_nesting_level = 500" | sudo tee >> <logical_path_you_have_found>`

This will add the directive --- shouldn't matter if it's in there twice, last one will prevail (correct me if i'm wrong!!)

**Comment by SarfrazS** [comment]
I have tested development branch of community, image file are downloadable from email box and agent panel.

**Comment by mverma16** [comment]
@SarfrazS, please read the whole issue thread and try to understand the issue. The issue is not with the file download. The error is not with downloading, it occurs while generating PDF of the tickets which has attachments. Please try with different type of attachment files and generate PDF o the tickets.

**Comment by SarfrazS** [comment]
Inline images are not showing please check it.

[dompdf_out.pdf](https://github.com/ladybirdweb/faveo-helpdesk/files/678623/dompdf_out.pdf)

I have tested  from development branch of  Faveo-Helpdesk.  (https://github.com/ladybirdweb/faveo-helpdesk.git)
