### ISSUE TITLE
Unable to view ticket details in user view

### ISSUE THREAD

**Issue by bartheid** [ladybirdweb/faveo-helpdesk#562]
- Faveo Version : 1.9.6
- PHP version : 7.0
- Database Driver & Version : mysql
- Server specification : 

#### Description:
When a user submits a ticket and tries to view it (after making an account), an error is displayed. When logging in, the user does see the list of created tickets. it's just when clicking one, the error is displayed. 

#### Steps To Reproduce:
1. create a ticket
2. login (as user) 
3. click any issue
--> "Something went wrong :("

#### Downloaded from
- [ ] master-branch

- [ ] development-branch

- [x] release-tag

#### 2 Exceptions from debug mode:

Whoops, looks like something went wrong.

2/2

ErrorException in 5ceb51a4168aa9ed3392b3c68e7e09965c002cc8.php line 100:

Trying to get property of non-object (View: /home/aqualed/domains/aqualedsupport.com/public_html/resources/views/themes/default1/client/helpdesk/ckeckticket.blade.php)

1. in 5ceb51a4168aa9ed3392b3c68e7e09965c002cc8.php line 100
2.at CompilerEngine->handleViewException(object(ErrorException), '1') in PhpEngine.php line 44
3.at PhpEngine->evaluatePath('/home/aqualed/domains/aqualedsupport.com/public_html/storage/framework/views/5ceb51a4168aa9ed3392b3c68e7e09965c002cc8.php', array('__env' => object(Factory), 'app' => object(Application), 'errors' => object(ViewErrorBag), 'id' => 'eyJpdiI6InV0czdYM3ZRMElKRXh0Rlc1c3BOSEE9PSIsInZhbHVlIjoiVVIzRmFpdkxcLzhnZXo1YkNmaWJHVVE9PSIsIm1hYyI6ImIxMDgyYmY0MWZhZDI1YTRiYjg0YzY2ZWQyM2Q1NzIxYjcwOTJmNDBmZGZjZGUyYmExMDFkZjBkMzgxYzcyNjEifQ==', 'common_setting' => object(CommonSettings))) in CompilerEngine.php line 59
4.at CompilerEngine->get('/home/aqualed/domains/aqualedsupport.com/public_html/resources/views/themes/default1/client/helpdesk/ckeckticket.blade.php', array('__env' => object(Factory), 'app' => object(Application), 'errors' => object(ViewErrorBag), 'id' => 'eyJpdiI6InV0czdYM3ZRMElKRXh0Rlc1c3BOSEE9PSIsInZhbHVlIjoiVVIzRmFpdkxcLzhnZXo1YkNmaWJHVVE9PSIsIm1hYyI6ImIxMDgyYmY0MWZhZDI1YTRiYjg0YzY2ZWQyM2Q1NzIxYjcwOTJmNDBmZGZjZGUyYmExMDFkZjBkMzgxYzcyNjEifQ==', 'common_setting' => object(CommonSettings))) in View.php line 149
5.at View->getContents() in View.php line 120
6.at View->renderContents() in View.php line 85
7.at View->render() in Response.php line 53
8.at Response->setContent(object(View)) in Response.php line 201
9.at Response->__construct(object(View)) in Router.php line 1085
10.at Router->prepareResponse(object(Request), object(View)) in ControllerDispatcher.php line 94
11.at ControllerDispatcher->Illuminate\Routing\{closure}(object(Request))
12.at call_user_func(object(Closure), object(Request)) in Pipeline.php line 52
13.at Pipeline->Illuminate\Routing\{closure}(object(Request)) in Authenticate.php line 54
14.at Authenticate->handle(object(Request), object(Closure))
15.at call_user_func_array(array(object(Authenticate), 'handle'), array(object(Request), object(Closure))) in Pipeline.php line 136
16.at Pipeline->Illuminate\Pipeline\{closure}(object(Request))
17.at call_user_func(object(Closure), object(Request)) in Pipeline.php line 32
18.at Pipeline->Illuminate\Routing\{closure}(object(Request)) in CheckBoard.php line 27
19.at CheckBoard->handle(object(Request), object(Closure))
20.at call_user_func_array(array(object(CheckBoard), 'handle'), array(object(Request), object(Closure))) in Pipeline.php line 136
21.at Pipeline->Illuminate\Pipeline\{closure}(object(Request))
22.at call_user_func(object(Closure), object(Request)) in Pipeline.php line 32
23.at Pipeline->Illuminate\Routing\{closure}(object(Request))
24.at call_user_func(object(Closure), object(Request)) in Pipeline.php line 102
25.at Pipeline->then(object(Closure)) in ControllerDispatcher.php line 96
26.at ControllerDispatcher->callWithinStack(object(GuestController), object(Route), object(Request), 'get_ticket_email') in ControllerDispatcher.php line 54
27.at ControllerDispatcher->dispatch(object(Route), object(Request), 'App\Http\Controllers\Client\helpdesk\GuestController', 'get_ticket_email') in Route.php line 174
28.at Route->runController(object(Request)) in Route.php line 140
29.at Route->run(object(Request)) in Router.php line 724
30.at Router->Illuminate\Routing\{closure}(object(Request))
31.at call_user_func(object(Closure), object(Request)) in Pipeline.php line 52
32.at Pipeline->Illuminate\Routing\{closure}(object(Request)) in LanguageMiddleware.php line 21
33.at LanguageMiddleware->handle(object(Request), object(Closure))
34.at call_user_func_array(array(object(LanguageMiddleware), 'handle'), array(object(Request), object(Closure))) in Pipeline.php line 136
35.at Pipeline->Illuminate\Pipeline\{closure}(object(Request))
36.at call_user_func(object(Closure), object(Request)) in Pipeline.php line 32
37.at Pipeline->Illuminate\Routing\{closure}(object(Request)) in VerifyCsrfToken.php line 64
38.at VerifyCsrfToken->handle(object(Request), object(Closure)) in VerifyCsrfToken.php line 30
39.at VerifyCsrfToken->handle(object(Request), object(Closure))
40.at call_user_func_array(array(object(VerifyCsrfToken), 'handle'), array(object(Request), object(Closure))) in Pipeline.php line 136
41.at Pipeline->Illuminate\Pipeline\{closure}(object(Request))
42.at call_user_func(object(Closure), object(Request)) in Pipeline.php line 32
43.at Pipeline->Illuminate\Routing\{closure}(object(Request)) in ShareErrorsFromSession.php line 49
44.at ShareErrorsFromSession->handle(object(Request), object(Closure))
45.at call_user_func_array(array(object(ShareErrorsFromSession), 'handle'), array(object(Request), object(Closure))) in Pipeline.php line 136
46.at Pipeline->Illuminate\Pipeline\{closure}(object(Request))
47.at call_user_func(object(Closure), object(Request)) in Pipeline.php line 32
48.at Pipeline->Illuminate\Routing\{closure}(object(Request)) in StartSession.php line 64
49.at StartSession->handle(object(Request), object(Closure))
50.at call_user_func_array(array(object(StartSession), 'handle'), array(object(Request), object(Closure))) in Pipeline.php line 136
51.at Pipeline->Illuminate\Pipeline\{closure}(object(Request))
52.at call_user_func(object(Closure), object(Request)) in Pipeline.php line 32
53.at Pipeline->Illuminate\Routing\{closure}(object(Request)) in AddQueuedCookiesToResponse.php line 37
54.at AddQueuedCookiesToResponse->handle(object(Request), object(Closure))
55.at call_user_func_array(array(object(AddQueuedCookiesToResponse), 'handle'), array(object(Request), object(Closure))) in Pipeline.php line 136
56.at Pipeline->Illuminate\Pipeline\{closure}(object(Request))
57.at call_user_func(object(Closure), object(Request)) in Pipeline.php line 32
58.at Pipeline->Illuminate\Routing\{closure}(object(Request)) in EncryptCookies.php line 59
59.at EncryptCookies->handle(object(Request), object(Closure))
60.at call_user_func_array(array(object(EncryptCookies), 'handle'), array(object(Request), object(Closure))) in Pipeline.php line 136
61.at Pipeline->Illuminate\Pipeline\{closure}(object(Request))
62.at call_user_func(object(Closure), object(Request)) in Pipeline.php line 32
63.at Pipeline->Illuminate\Routing\{closure}(object(Request)) in CheckForMaintenanceMode.php line 44
64.at CheckForMaintenanceMode->handle(object(Request), object(Closure))
65.at call_user_func_array(array(object(CheckForMaintenanceMode), 'handle'), array(object(Request), object(Closure))) in Pipeline.php line 136
66.at Pipeline->Illuminate\Pipeline\{closure}(object(Request))
67.at call_user_func(object(Closure), object(Request)) in Pipeline.php line 32
68.at Pipeline->Illuminate\Routing\{closure}(object(Request))
69.at call_user_func(object(Closure), object(Request)) in Pipeline.php line 102
70.at Pipeline->then(object(Closure)) in Router.php line 726
71.at Router->runRouteWithinStack(object(Route), object(Request)) in Router.php line 699
72.at Router->dispatchToRoute(object(Request)) in Router.php line 675
73.at Router->dispatch(object(Request)) in Kernel.php line 246
74.at Kernel->Illuminate\Foundation\Http\{closure}(object(Request))
75.at call_user_func(object(Closure), object(Request)) in Pipeline.php line 52
76.at Pipeline->Illuminate\Routing\{closure}(object(Request)) in Debugbar.php line 51
77.at Debugbar->handle(object(Request), object(Closure))
78.at call_user_func_array(array(object(Debugbar), 'handle'), array(object(Request), object(Closure))) in Pipeline.php line 136
79.at Pipeline->Illuminate\Pipeline\{closure}(object(Request))
80.at call_user_func(object(Closure), object(Request)) in Pipeline.php line 32
81.at Pipeline->Illuminate\Routing\{closure}(object(Request)) in CheckForMaintenanceMode.php line 44
82.at CheckForMaintenanceMode->handle(object(Request), object(Closure))
83.at call_user_func_array(array(object(CheckForMaintenanceMode), 'handle'), array(object(Request), object(Closure))) in Pipeline.php line 136
84.at Pipeline->Illuminate\Pipeline\{closure}(object(Request))
85.at call_user_func(object(Closure), object(Request)) in Pipeline.php line 32
86.at Pipeline->Illuminate\Routing\{closure}(object(Request))
87.at call_user_func(object(Closure), object(Request)) in Pipeline.php line 102
88.at Pipeline->then(object(Closure)) in Kernel.php line 132
89.at Kernel->sendRequestThroughRouter(object(Request)) in Kernel.php line 99
90.at Kernel->handle(object(Request)) in index.php line 52

1/2

ErrorException in 5ceb51a4168aa9ed3392b3c68e7e09965c002cc8.php line 100:

Trying to get property of non-object

1. in 5ceb51a4168aa9ed3392b3c68e7e09965c002cc8.php line 100
2.at HandleExceptions->handleError('8', 'Trying to get property of non-object', '/home/aqualed/domains/aqualedsupport.com/public_html/storage/framework/views/5ceb51a4168aa9ed3392b3c68e7e09965c002cc8.php', '100', array('__path' => '/home/aqualed/domains/aqualedsupport.com/public_html/storage/framework/views/5ceb51a4168aa9ed3392b3c68e7e09965c002cc8.php', '__data' => array('__env' => object(Factory), 'app' => object(Application), 'errors' => object(ViewErrorBag), 'id' => 'eyJpdiI6InV0czdYM3ZRMElKRXh0Rlc1c3BOSEE9PSIsInZhbHVlIjoiVVIzRmFpdkxcLzhnZXo1YkNmaWJHVVE9PSIsIm1hYyI6ImIxMDgyYmY0MWZhZDI1YTRiYjg0YzY2ZWQyM2Q1NzIxYjcwOTJmNDBmZGZjZGUyYmExMDFkZjBkMzgxYzcyNjEifQ==', 'common_setting' => object(CommonSettings)), 'obLevel' => '1', '__env' => object(Factory), 'app' => object(Application), 'errors' => object(ViewErrorBag), 'id' => 'eyJpdiI6InV0czdYM3ZRMElKRXh0Rlc1c3BOSEE9PSIsInZhbHVlIjoiVVIzRmFpdkxcLzhnZXo1YkNmaWJHVVE9PSIsIm1hYyI6ImIxMDgyYmY0MWZhZDI1YTRiYjg0YzY2ZWQyM2Q1NzIxYjcwOTJmNDBmZGZjZGUyYmExMDFkZjBkMzgxYzcyNjEifQ==', 'common_setting' => object(CommonSettings), 'tickets' => object(Tickets), 'thread' => object(Ticket_Thread), 'ratings' => object(Collection), 'rating' => object(Rating), 'rating_value' => null, 'ratingval' => '0', 'i' => '6', 'priority' => object(Ticket_Priority), 'sla' => '3', 'SlaPlan' => null)) in 5ceb51a4168aa9ed3392b3c68e7e09965c002cc8.php line 100
3.at include('/home/aqualed/domains/aqualedsupport.com/public_html/storage/framework/views/5ceb51a4168aa9ed3392b3c68e7e09965c002cc8.php') in PhpEngine.php line 42
4.at PhpEngine->evaluatePath('/home/aqualed/domains/aqualedsupport.com/public_html/storage/framework/views/5ceb51a4168aa9ed3392b3c68e7e09965c002cc8.php', array('__env' => object(Factory), 'app' => object(Application), 'errors' => object(ViewErrorBag), 'id' => 'eyJpdiI6InV0czdYM3ZRMElKRXh0Rlc1c3BOSEE9PSIsInZhbHVlIjoiVVIzRmFpdkxcLzhnZXo1YkNmaWJHVVE9PSIsIm1hYyI6ImIxMDgyYmY0MWZhZDI1YTRiYjg0YzY2ZWQyM2Q1NzIxYjcwOTJmNDBmZGZjZGUyYmExMDFkZjBkMzgxYzcyNjEifQ==', 'common_setting' => object(CommonSettings))) in CompilerEngine.php line 59
5.at CompilerEngine->get('/home/aqualed/domains/aqualedsupport.com/public_html/resources/views/themes/default1/client/helpdesk/ckeckticket.blade.php', array('__env' => object(Factory), 'app' => object(Application), 'errors' => object(ViewErrorBag), 'id' => 'eyJpdiI6InV0czdYM3ZRMElKRXh0Rlc1c3BOSEE9PSIsInZhbHVlIjoiVVIzRmFpdkxcLzhnZXo1YkNmaWJHVVE9PSIsIm1hYyI6ImIxMDgyYmY0MWZhZDI1YTRiYjg0YzY2ZWQyM2Q1NzIxYjcwOTJmNDBmZGZjZGUyYmExMDFkZjBkMzgxYzcyNjEifQ==', 'common_setting' => object(CommonSettings))) in View.php line 149
6.at View->getContents() in View.php line 120
7.at View->renderContents() in View.php line 85
8.at View->render() in Response.php line 53
9.at Response->setContent(object(View)) in Response.php line 201
10.at Response->__construct(object(View)) in Router.php line 1085
11.at Router->prepareResponse(object(Request), object(View)) in ControllerDispatcher.php line 94
12.at ControllerDispatcher->Illuminate\Routing\{closure}(object(Request))
13.at call_user_func(object(Closure), object(Request)) in Pipeline.php line 52
14.at Pipeline->Illuminate\Routing\{closure}(object(Request)) in Authenticate.php line 54
15.at Authenticate->handle(object(Request), object(Closure))
16.at call_user_func_array(array(object(Authenticate), 'handle'), array(object(Request), object(Closure))) in Pipeline.php line 136
17.at Pipeline->Illuminate\Pipeline\{closure}(object(Request))
18.at call_user_func(object(Closure), object(Request)) in Pipeline.php line 32
19.at Pipeline->Illuminate\Routing\{closure}(object(Request)) in CheckBoard.php line 27
20.at CheckBoard->handle(object(Request), object(Closure))
21.at call_user_func_array(array(object(CheckBoard), 'handle'), array(object(Request), object(Closure))) in Pipeline.php line 136
22.at Pipeline->Illuminate\Pipeline\{closure}(object(Request))
23.at call_user_func(object(Closure), object(Request)) in Pipeline.php line 32
24.at Pipeline->Illuminate\Routing\{closure}(object(Request))
25.at call_user_func(object(Closure), object(Request)) in Pipeline.php line 102
26.at Pipeline->then(object(Closure)) in ControllerDispatcher.php line 96
27.at ControllerDispatcher->callWithinStack(object(GuestController), object(Route), object(Request), 'get_ticket_email') in ControllerDispatcher.php line 54
28.at ControllerDispatcher->dispatch(object(Route), object(Request), 'App\Http\Controllers\Client\helpdesk\GuestController', 'get_ticket_email') in Route.php line 174
29.at Route->runController(object(Request)) in Route.php line 140
30.at Route->run(object(Request)) in Router.php line 724
31.at Router->Illuminate\Routing\{closure}(object(Request))
32.at call_user_func(object(Closure), object(Request)) in Pipeline.php line 52
33.at Pipeline->Illuminate\Routing\{closure}(object(Request)) in LanguageMiddleware.php line 21
34.at LanguageMiddleware->handle(object(Request), object(Closure))
35.at call_user_func_array(array(object(LanguageMiddleware), 'handle'), array(object(Request), object(Closure))) in Pipeline.php line 136
36.at Pipeline->Illuminate\Pipeline\{closure}(object(Request))
37.at call_user_func(object(Closure), object(Request)) in Pipeline.php line 32
38.at Pipeline->Illuminate\Routing\{closure}(object(Request)) in VerifyCsrfToken.php line 64
39.at VerifyCsrfToken->handle(object(Request), object(Closure)) in VerifyCsrfToken.php line 30
40.at VerifyCsrfToken->handle(object(Request), object(Closure))
41.at call_user_func_array(array(object(VerifyCsrfToken), 'handle'), array(object(Request), object(Closure))) in Pipeline.php line 136
42.at Pipeline->Illuminate\Pipeline\{closure}(object(Request))
43.at call_user_func(object(Closure), object(Request)) in Pipeline.php line 32
44.at Pipeline->Illuminate\Routing\{closure}(object(Request)) in ShareErrorsFromSession.php line 49
45.at ShareErrorsFromSession->handle(object(Request), object(Closure))
46.at call_user_func_array(array(object(ShareErrorsFromSession), 'handle'), array(object(Request), object(Closure))) in Pipeline.php line 136
47.at Pipeline->Illuminate\Pipeline\{closure}(object(Request))
48.at call_user_func(object(Closure), object(Request)) in Pipeline.php line 32
49.at Pipeline->Illuminate\Routing\{closure}(object(Request)) in StartSession.php line 64
50.at StartSession->handle(object(Request), object(Closure))
51.at call_user_func_array(array(object(StartSession), 'handle'), array(object(Request), object(Closure))) in Pipeline.php line 136
52.at Pipeline->Illuminate\Pipeline\{closure}(object(Request))
53.at call_user_func(object(Closure), object(Request)) in Pipeline.php line 32
54.at Pipeline->Illuminate\Routing\{closure}(object(Request)) in AddQueuedCookiesToResponse.php line 37
55.at AddQueuedCookiesToResponse->handle(object(Request), object(Closure))
56.at call_user_func_array(array(object(AddQueuedCookiesToResponse), 'handle'), array(object(Request), object(Closure))) in Pipeline.php line 136
57.at Pipeline->Illuminate\Pipeline\{closure}(object(Request))
58.at call_user_func(object(Closure), object(Request)) in Pipeline.php line 32
59.at Pipeline->Illuminate\Routing\{closure}(object(Request)) in EncryptCookies.php line 59
60.at EncryptCookies->handle(object(Request), object(Closure))
61.at call_user_func_array(array(object(EncryptCookies), 'handle'), array(object(Request), object(Closure))) in Pipeline.php line 136
62.at Pipeline->Illuminate\Pipeline\{closure}(object(Request))
63.at call_user_func(object(Closure), object(Request)) in Pipeline.php line 32
64.at Pipeline->Illuminate\Routing\{closure}(object(Request)) in CheckForMaintenanceMode.php line 44
65.at CheckForMaintenanceMode->handle(object(Request), object(Closure))
66.at call_user_func_array(array(object(CheckForMaintenanceMode), 'handle'), array(object(Request), object(Closure))) in Pipeline.php line 136
67.at Pipeline->Illuminate\Pipeline\{closure}(object(Request))
68.at call_user_func(object(Closure), object(Request)) in Pipeline.php line 32
69.at Pipeline->Illuminate\Routing\{closure}(object(Request))
70.at call_user_func(object(Closure), object(Request)) in Pipeline.php line 102
71.at Pipeline->then(object(Closure)) in Router.php line 726
72.at Router->runRouteWithinStack(object(Route), object(Request)) in Router.php line 699
73.at Router->dispatchToRoute(object(Request)) in Router.php line 675
74.at Router->dispatch(object(Request)) in Kernel.php line 246
75.at Kernel->Illuminate\Foundation\Http\{closure}(object(Request))
76.at call_user_func(object(Closure), object(Request)) in Pipeline.php line 52
77.at Pipeline->Illuminate\Routing\{closure}(object(Request)) in Debugbar.php line 51
78.at Debugbar->handle(object(Request), object(Closure))
79.at call_user_func_array(array(object(Debugbar), 'handle'), array(object(Request), object(Closure))) in Pipeline.php line 136
80.at Pipeline->Illuminate\Pipeline\{closure}(object(Request))
81.at call_user_func(object(Closure), object(Request)) in Pipeline.php line 32
82.at Pipeline->Illuminate\Routing\{closure}(object(Request)) in CheckForMaintenanceMode.php line 44
83.at CheckForMaintenanceMode->handle(object(Request), object(Closure))
84.at call_user_func_array(array(object(CheckForMaintenanceMode), 'handle'), array(object(Request), object(Closure))) in Pipeline.php line 136
85.at Pipeline->Illuminate\Pipeline\{closure}(object(Request))
86.at call_user_func(object(Closure), object(Request)) in Pipeline.php line 32
87.at Pipeline->Illuminate\Routing\{closure}(object(Request))
88.at call_user_func(object(Closure), object(Request)) in Pipeline.php line 102
89.at Pipeline->then(object(Closure)) in Kernel.php line 132
90.at Kernel->sendRequestThroughRouter(object(Request)) in Kernel.php line 99
91.at Kernel->handle(object(Request)) in index.php line 52

**Comment by mverma16** [comment]
Closing the issue as @bartheid's problem has been solved and an active issue #564 has been created for the same.

**Comment by ikrudolf** [comment]
This issue is still active but closed twice without resolution? 
https://github.com/ladybirdweb/faveo-helpdesk/issues/562
https://github.com/ladybirdweb/faveo-helpdesk/issues/564
